/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EvaluacionDesempeñoOperativo;

import BD.BD;
import BDQueryEmpleados.IngresoEmpleado;
import Clases.Evaluacion.BDEvaluacion;
import Clases.Evaluacion.ClassEvaluacion;
import Clases.empleados.ListaMaestro;
import static Formuarios.Inicio.Pane1;
import Formularios_Maestro_empleados.FormularioMaestroEditar;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author jluis
 */
public class NuevaEvaluacion extends javax.swing.JInternalFrame {

    int idlistaempleado;
    int face;
    int codigo;

    /**
     * Creates new form NuevaEvaluacion
     */
    public NuevaEvaluacion() {
        initComponents();
    }

    private void buscar(){
    
     try {
            ClassEvaluacion p = BDEvaluacion.buscarEmple(codigo);
            nombre.setText(p.getNombres()+' '+p.getApellidos());
            PUESTO.setText(p.getPuesto());
            DEPTO.setText(p.getDepto());
           ;
      } catch (Exception e) { JOptionPane.showMessageDialog(null, "ERROR AL OBTENER EL EMPLEADO A EDITAR "+e);
          }
    
    
    }
    
    
    
    
    
    
    
    private void ValidarExistencia() {

        try {

            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select COUNT(codigo) from alistaempleados where codigo=" + CODIGO.getText());
            rs.next();
            int c = rs.getInt("count(codigo)");
            if (CODIGO.getText() == "") {
                JOptionPane.showMessageDialog(null, "INGRESE EL CODIGO");
            } else if (c == 1) {
               
            } else {
                JOptionPane.showMessageDialog(null, "EL CODIGO EMPLEADO NO EXITE INTENTE DE NUEVO...");
            }

        } catch (Exception e) {
            System.out.println("ERROR " + e);
        }

    }

    private void guardarEvaluacion() {
        try {
            ClassEvaluacion l = new ClassEvaluacion();
            l.setId_listaempleados(idlistaempleado);
            if (face1.isSelected()) {
                face = 1;
            } else if (face2.isSelected()) {
                face = 2;
            } else if (face3.isSelected()) {
                face = 3;
            }
            l.setFace(face);
            l.setFecha(fechaEvaluacion.getDate());
            Clases.Evaluacion.BDEvaluacion.insertarEvaluacion(l);
            JOptionPane.showMessageDialog(null, "EMPLEADO INGRESADO");
            //limpiar();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR INGRESO EMPLEADOS" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        DEPTO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PUESTO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        face1 = new javax.swing.JCheckBox();
        face2 = new javax.swing.JCheckBox();
        face3 = new javax.swing.JCheckBox();
        fechaEvaluacion = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("INGRESO NUEVA EVALUACION");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CODIGO DEL EMPLEADO");

        CODIGO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL EMPLEADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("DEPARTAMENTO");

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        DEPTO.setEditable(false);
        DEPTO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("PUESTO");

        PUESTO.setEditable(false);
        PUESTO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DEPTO)
                    .addComponent(nombre)
                    .addComponent(PUESTO)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(0, 278, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DEPTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("FECHA ");

        face1.setText("FACE 1");
        face1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                face1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                face1MousePressed(evt);
            }
        });

        face2.setText("FACE 2");
        face2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                face2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                face2MousePressed(evt);
            }
        });

        face3.setText("FACE 3");
        face3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                face3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                face3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                face3MousePressed(evt);
            }
        });

        fechaEvaluacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CODIGO, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(fechaEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(face1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(face2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(face3))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(face1)
                        .addComponent(face2)
                        .addComponent(face3)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void face1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face1MouseClicked
        face2.setSelected(false);
        face3.setSelected(false);
    }//GEN-LAST:event_face1MouseClicked

    private void face2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face2MouseClicked
        face1.setSelected(false);
        face3.setSelected(false);
    }//GEN-LAST:event_face2MouseClicked

    private void face3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face3MouseClicked
        face2.setSelected(false);
        face1.setSelected(false);
    }//GEN-LAST:event_face3MouseClicked

    private void face1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face1MouseEntered

    }//GEN-LAST:event_face1MouseEntered

    private void face2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face2MouseEntered

    }//GEN-LAST:event_face2MouseEntered

    private void face3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face3MouseEntered

    }//GEN-LAST:event_face3MouseEntered

    private void face1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face1MousePressed
        face2.setSelected(false);
        face3.setSelected(false);
    }//GEN-LAST:event_face1MousePressed

    private void face2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face2MousePressed
        face1.setSelected(false);
        face3.setSelected(false);
    }//GEN-LAST:event_face2MousePressed

    private void face3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_face3MousePressed
        face2.setSelected(false);
        face1.setSelected(false);
    }//GEN-LAST:event_face3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CODIGO;
    private javax.swing.JTextField DEPTO;
    private javax.swing.JTextField PUESTO;
    private javax.swing.JCheckBox face1;
    private javax.swing.JCheckBox face2;
    private javax.swing.JCheckBox face3;
    private com.toedter.calendar.JDateChooser fechaEvaluacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
