/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formuarios;

import java.util.ArrayList;
import Clases.empleados.Empleados;
import BD.*;
import javax.swing.JOptionPane;
import sun.management.resources.agent;

/**
 *
 * @author jluis
 */
public class ListaEmpleados extends javax.swing.JInternalFrame {
    int depto;
    
    /**
     * Creates new form Empleados
     */
    public ListaEmpleados() {
        initComponents();
        TablaNombre();
        TablaAgregado();
        agregartododepto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    
     public void AgregarAlista() {

        try {
            int codigo = (Integer.parseInt(String.valueOf(empleados.getModel().getValueAt(empleados.getSelectedRow(), 0))));
            Empleados m = new Empleados();
            m.setCodigo(codigo);
            Consultas.agregaralista(m);
            /* System.out.println("1 = "+compo);
               System.out.println("2 = "+id_trabajo);
               System.out.println("1 = "+(Integer.parseInt(CANTIDAD.getText())*cantidad));*/
            TablaNombre();
            TablaAgregado();
        } catch (Exception e) {
            System.out.println("Error BD:" + e);
        }

    }
    
    
    public void Eliminardelista() {

        try {
            int codigo = (Integer.parseInt(String.valueOf(empleadosagregados.getModel().getValueAt(empleadosagregados.getSelectedRow(), 0))));
            Empleados m = new Empleados();
            m.setCodigo(codigo);
            Consultas.Eliminarlista(m);
            TablaNombre();
            TablaAgregado();
        } catch (Exception e) {
            System.out.println("Error BD:" + e);
        }

    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        agregartododepto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        empleados = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        empleadosagregados = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        departamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        codigos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigosActionPerformed(evt);
            }
        });
        codigos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigosKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CODIGOS");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        agregartododepto.setText("AGREGAR TODO DEPTO");
        agregartododepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregartododeptoActionPerformed(evt);
            }
        });

        empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Puesto"
            }
        ));
        empleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(empleados);

        jButton4.setText("CANCELAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("LISTADO DE TODOS LOS EMPLEADOS");

        jButton6.setText("AGREGAR TODA LA LISTA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(agregartododepto)
                        .addGap(45, 45, 45)
                        .addComponent(jButton6)
                        .addGap(52, 52, 52)
                        .addComponent(jButton4)
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregartododepto)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(21, 21, 21))
        );

        empleadosagregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Puesto"
            }
        ));
        empleadosagregados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        empleadosagregados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadosagregadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(empleadosagregados);

        jButton5.setText("ELIMINAR TODOS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("LISTADO DE EMPLEADOS AGREGADOS PARA LISTADOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(201, 201, 201))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DEPARTAMENTO");

        departamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR...", "ADMINISTRACION", "BODEGA", "CHIPS", "INSPECCION VISUAL", "MANTENIMIENTO", "SOLDER DIP", "TESTING", "TRANSFORMADORES" }));
        departamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departamentoMouseClicked(evt);
            }
        });
        departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(departamento, javax.swing.GroupLayout.Alignment.LEADING, 0, 268, Short.MAX_VALUE)
                            .addComponent(codigos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigosKeyTyped
 
    }//GEN-LAST:event_codigosKeyTyped

    private void codigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigosActionPerformed
        departamento.setSelectedItem("SELECCIONAR...");
        agregartododepto.setEnabled(false);
        nombre.setText("");
        TablaCodigos();
    }//GEN-LAST:event_codigosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        try {
            Empleados m = new Empleados();
            m.setEstado(1);
            Consultas.eleminartododelista(m);
        } catch (Exception e) {System.out.println("error al eliminar de la lista"+e);
        }
       codigos.setText("");
       nombre.setText("");
       departamento.setSelectedItem("SELECCIONAR...");
       agregartododepto.setEnabled(false);
       TablaNombre();
       TablaAgregado();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        departamento.setSelectedItem("SELECCIONAR...");
        agregartododepto.setEnabled(false);
        nombre.setText("");
        TablaCodigos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoActionPerformed
         
        if (departamento.getSelectedItem().toString().equalsIgnoreCase("SELECCIONAR...")) {
             depto = 0;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("ADMINISTRACION")){
             depto = 1;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("BODEGA")){
             depto = 2;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("CHIPS")){
             depto = 3;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("INSPECCION VISUAL")){
             depto = 4;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("MANTENIMIENTO")){
             depto = 5;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("SOLDER DIP")){
             depto = 6;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("TESTING")){
             depto = 7;
        }else if (departamento.getSelectedItem().toString().equalsIgnoreCase("TRANSFORMADORES")){
             depto = 8;
        }
        TablaDepartamento();
        agregartododepto.setEnabled(true);
    
    }//GEN-LAST:event_departamentoActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        departamento.setSelectedItem("SELECCIONAR...");
        agregartododepto.setEnabled(false);
        codigos.setText("");
        TablaNombre();
    }//GEN-LAST:event_nombreKeyTyped

    private void departamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentoMouseClicked
       codigos.setText("");
       nombre.setText("");
    }//GEN-LAST:event_departamentoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
       codigos.setText("");
       nombre.setText("");
       departamento.setSelectedItem("SELECCIONAR...");
       agregartododepto.setEnabled(false);
       TablaNombre();
       TablaAgregado();
       agregartododepto.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void empleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosMouseClicked
        
        
        if (evt.getClickCount() > 1) {
            
            AgregarAlista();
            
        }
        
        
    }//GEN-LAST:event_empleadosMouseClicked

    private void agregartododeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregartododeptoActionPerformed
        
        try {
            Empleados m = new Empleados();
            m.setDepto(depto);
            Consultas.agregardepto(m);
        } catch (Exception e) {System.out.println("error al agregar todo el departamento  "+e);
        }
       TablaNombre();
       TablaAgregado();
       
       codigos.setText("");
       nombre.setText("");
       departamento.setSelectedItem("SELECCIONAR...");
       agregartododepto.setEnabled(false);
    
    }//GEN-LAST:event_agregartododeptoActionPerformed

    private void empleadosagregadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosagregadosMouseClicked
         if (evt.getClickCount() > 1) {
            
            Eliminardelista();
            
        }
    }//GEN-LAST:event_empleadosagregadosMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
        try {
            Empleados m = new Empleados();
            m.setEstado(2);
            Consultas.agregartodoalista(m);
        } catch (Exception e) {System.out.println("error al agregar todo el departamento  "+e);
        }
       TablaNombre();
       TablaAgregado();
       codigos.setText("");
       nombre.setText("");
       departamento.setSelectedItem("SELECCIONAR...");
       agregartododepto.setEnabled(false);
       
        
    }//GEN-LAST:event_jButton6ActionPerformed

     private void TablaCodigos() {

        ArrayList<Empleados> result = Consultas.ListarEmpleadosCodigo(codigos.getText());
        recagarTabla(result);
    }
     
    private void TablaDepartamento() {

        ArrayList<Empleados> result = Consultas.ListarEmpleadosDepto(depto);
        recagarTabla(result);
    } 
    
    private void TablaNombre(){

        ArrayList<Empleados> result = Consultas.ListarEmpleadosNombre(nombre.getText());
        recagarTabla(result);
    }
     
    private void recagarTabla(ArrayList<Empleados> list) {

        Object[][] dato = new Object[list.size()][3];
        int f = 0;
        for (Empleados a : list) {
            dato[f][0] = a.getCodigo();
            dato[f][1] = a.getNombre();
            dato[f][2] = a.getPuesto();
            f++;
        }
        empleados.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                    "Codigo","Nombre","Puesto"
                }) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                });
    }
 
    private void TablaAgregado(){

        ArrayList<Empleados> result = Consultas.ListarEmpleadosAgregados();
        recagarTablaAgregados(result);
    }
     
    private void recagarTablaAgregados(ArrayList<Empleados> list) {

        Object[][] dato = new Object[list.size()][3];
        int f = 0;
        for (Empleados a : list) {
            dato[f][0] = a.getCodigo();
            dato[f][1] = a.getNombre();
            dato[f][2] = a.getPuesto();
            f++;
        }
        empleadosagregados.setModel(new javax.swing.table.DefaultTableModel(
                dato,
                new String[]{
                    "Codigo","Nombre","Puesto"
                }) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEmpleados().setVisible(true);
            }
        });
        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregartododepto;
    private javax.swing.JTextField codigos;
    private javax.swing.JComboBox<String> departamento;
    private javax.swing.JTable empleados;
    private javax.swing.JTable empleadosagregados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
