/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reloj;

import BD.BD;
import BDreloj.ClassReloj;
import BDreloj.QuerysReloj;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jluis
 */
public class Asistencia_Dia_Permisos extends javax.swing.JInternalFrame {
    String fecha1;
    /**
     * Creates new form Faltas_Dia
     */
    public Asistencia_Dia_Permisos() {
        initComponents();
        Calendar c2 = new GregorianCalendar();
        JD_Fecha.setCalendar(c2);
        fecha();
     

        
    }
    
   private void fecha(){
   
    Date date = JD_Fecha.getDate();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
    fecha1 = sdf.format(date);
   
       
   }
    
    
    
    private void ListarAsistenciaPermisos(){
        fecha();
        System.out.println("TEST "+fecha1);
        ArrayList<ClassReloj> result = QuerysReloj.ListarAsistenciaPermisos(fecha1);
        RecargarTabla(result);  
    }
     private void RecargarTabla(ArrayList<ClassReloj> list) {
         
              Object[][] datos = new Object[list.size()][6];
              int i = 0;
              for(ClassReloj t : list)
              {
                  datos[i][0] = t.getCodigo();
                  datos[i][1] = t.getNombre();
                  datos[i][2] = t.getFecha();
                  datos[i][3] = t.getHorain();
                  datos[i][4] = t.getHoraout();
                  datos[i][5] = t.getDepartamento();
                  
                  
                  i++;
              }    
             ListaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "CODIGO","NOMBRE","FECHA","HORA DE INGRESO","HORA DE SALIDA","DEPARTAMENTO"
 
             })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = ListaEmpleados.getColumn("CODIGO");
             columna1.setPreferredWidth(-10);
             TableColumn columna2 = ListaEmpleados.getColumn("NOMBRE");
             columna2.setPreferredWidth(150);
             TableColumn columna3 = ListaEmpleados.getColumn("FECHA");
             columna3.setPreferredWidth(10);
             TableColumn columna4 = ListaEmpleados.getColumn("HORA DE INGRESO");
             columna4.setPreferredWidth(25);
             TableColumn columna5 = ListaEmpleados.getColumn("HORA DE SALIDA");
             columna5.setPreferredWidth(25);
             TableColumn columna6 = ListaEmpleados.getColumn("DEPARTAMENTO");
             columna6.setPreferredWidth(150);
             
}
   
     
     
private void ImprimeReporte(){
        //id_evaluacion = (Integer.parseInt(String.valueOf(NoImprime.getModel().getValueAt(NoImprime.getSelectedRow(),0))));
          BD con= new BD();
         Connection conexion= con.getConnection();
        try {
            JasperReport jasperReport=(JasperReport)JRLoader.loadObjectFromFile("\\\\SRVANATEK\\Bases de Datos\\Sistema\\Recursos Humanos\\Reloj\\AsistenciaDiaIncompleto.jasper");
            Map parametros= new HashMap();
            parametros.put("FECHA", fecha1);
            JasperPrint print = JasperFillManager.fillReport(jasperReport,parametros, conexion);
            JasperViewer view = new JasperViewer(print,false);
            view.setVisible(true);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "ERROR EJECUTAR REPORTES =  "+e);
        }
    }     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaEmpleados = new javax.swing.JTable();
        JD_Fecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BUSCAR = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("REPORTE DE ASISTENCIA ");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clock (2).png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REPORTE DE ASISTENCIA POR DIA INCOMPLETO");

        ListaEmpleados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ListaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "FECHA", "HORA INGRESO", "HORA SALIDA", "DEPARTAMENTO"
            }
        ));
        ListaEmpleados.setIntercellSpacing(new java.awt.Dimension(10, 1));
        ListaEmpleados.setRowHeight(26);
        jScrollPane1.setViewportView(ListaEmpleados);

        JD_Fecha.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                JD_FechaInputMethodTextChanged(evt);
            }
        });
        JD_Fecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JD_FechaPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("FECHA");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComponenteImagenes/Print.png"))); // NOI18N
        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom.png"))); // NOI18N
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JD_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BUSCAR))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(522, 522, 522)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JD_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BUSCAR, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JD_FechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JD_FechaPropertyChange
         
    }//GEN-LAST:event_JD_FechaPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImprimeReporte();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JD_FechaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JD_FechaInputMethodTextChanged
       
    }//GEN-LAST:event_JD_FechaInputMethodTextChanged

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        ListarAsistenciaPermisos();
    }//GEN-LAST:event_BUSCARActionPerformed

    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    private com.toedter.calendar.JDateChooser JD_Fecha;
    private javax.swing.JTable ListaEmpleados;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
